name: "Real-Time HDR SRGAN Pipeline"
guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version: "1.0.0.0"
targetAbi: "10.11.5.0"
framework: "net9.0"
owner: "Real-Time HDR SRGAN Pipeline"
overview: "Real-time HDR upscaling with NVIDIA GPU support"
description: "Adds real-time HDR upscaling capabilities to Jellyfin transcoding using NVIDIA GPUs"
category: "Transcoding"
artifacts:
  - "Jellyfin.Plugin.RealTimeHdrSrgan.dll"
changelog: "Initial release"
